### ISSUE TITLE
No ability to exclude certain files when using Copy?

### ISSUE THREAD

**Issue by grantlucas** [crysalead/dir#1]
In the current implementation, `$options['exclude']` is [unset when copying](https://github.com/crysalead/dir/blob/master/src/Dir.php#L198). Is there any reason why this is unset? It would be very useful to be able to limit which files are copied over when copying a directory.

For example, copy the contents of one folder to another but _only_ copy the image files.

**Comment by jails** [comment]
Fixed in https://github.com/crysalead/dir/commit/842e98459af600db237caaff1e0c0f59a275a171
