### ISSUE TITLE
Windows paths bug in Dir.php:260

### ISSUE THREAD

**Issue by ewesseloh** [crysalead/dir#3]
you should escape strings for preg_replace

```
$target = preg_replace('~^' . preg_quote($root) . '~', '', $path);
```

on Windows it does not replace the root path.

[see here](https://github.com/crysalead/dir/blob/master/src/Dir.php#L260)

**Comment by jails** [comment]
Not sure to get what you mean.
Can you give me an example with a real path ? What is the actual result and what you expected ?

**Comment by ewesseloh** [comment]
Hello Simon,

yes, assume $path is „c:\dir\file.txt”
when concatenated as string to regex pattern some backslashes act as modifiers so “c:\dir” becomes actually “c:[0-9]ir”, which is wrong.

And even if you escape that path string with regex_qoute() this does not solve all problems with windows paths.
There is one more:

For example we want to copy “C:\dir\” to “D:\dir”, the iterator resolves all files and returns an array:
Array(
    “C:\dir/subdir/file1”,
    “C:\dir/file2”,
);

So replacement fails again, since “/” can’t be matched by “\”.
It results in concatenation of dest path with original source path and becomes something like “D:\dir\C:\dir/subdir/file”, which is simply wrong.

Best regards

Eugen Wesseloh

Von: Simon JAILLET [mailto:notifications@github.com]
Gesendet: Mittwoch, 28. September 2016 12:07
An: crysalead/dir
Cc: Eugen Wesseloh; Author
Betreff: Re: [crysalead/dir] Windows paths bug in Dir.php:260 (#3)

Not sure to get what you mean.
Can you give me an example with a real path ? What is the actual result and what you expected ?

**Comment by jails** [comment]
Good catch, so does using:

``` php
$target = preg_replace('~^' . preg_quote(rtrim($root, $ds)) . '~', '', $path);
```

works for both cases ?

**Comment by ewesseloh** [comment]
Yes. we have a windows webserver, so we had to fix that first.
You may experience problems even on *nix systems without that fix, just try some regex meta characters in filenames (like "fine.+name").

**Comment by jails** [comment]
Fixed in https://github.com/crysalead/dir/commit/bb91ed1e8d2db50ac88a62b8ba7b2afdbf94af97
