### ISSUE TITLE
I can't use autoload.php in composer

### ISSUE THREAD

**Issue by dotku** [crysalead/dir#4]
I use composer to install this program, but I can't use it directly. I got following error:

`Fatal error: Class 'Dir' not found in /var/www/html/index_csl.php on line 24`

**Comment by jails** [comment]
Hi, you need to add the required use statement at the top of your php file `use Lead\Dir\Dir;` to be able to use it.

**Comment by shturnev** [comment]
> Hi, you need to add the required use statement at the top of your php file `use Lead\Dir\Dir;` to be able to use it.

You need to add this in README. Because it's not obvious. Thanks
